// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFruzl8gY2p8WHfVzC-fKK3pJGeDSJTzY',
    appId: '1:296711123301:web:db7e3bd27d6349c4a8318c',
    messagingSenderId: '296711123301',
    projectId: 'gymapp-8dacc',
    authDomain: 'gymapp-8dacc.firebaseapp.com',
    storageBucket: 'gymapp-8dacc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5cqukkIAycVYbEYxkQ_-InTlQu6614h8',
    appId: '1:296711123301:android:923ff8f51bb2610ea8318c',
    messagingSenderId: '296711123301',
    projectId: 'gymapp-8dacc',
    storageBucket: 'gymapp-8dacc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0VfzPB2LadBIDW2XTygFlGZ_5FgTZLBc',
    appId: '1:296711123301:ios:21ada060ee9a0072a8318c',
    messagingSenderId: '296711123301',
    projectId: 'gymapp-8dacc',
    storageBucket: 'gymapp-8dacc.firebasestorage.app',
    iosBundleId: 'com.churiah.gymAppV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0VfzPB2LadBIDW2XTygFlGZ_5FgTZLBc',
    appId: '1:296711123301:ios:de0ad88f9c7a612fa8318c',
    messagingSenderId: '296711123301',
    projectId: 'gymapp-8dacc',
    storageBucket: 'gymapp-8dacc.firebasestorage.app',
    iosBundleId: 'com.example.gymAppV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFruzl8gY2p8WHfVzC-fKK3pJGeDSJTzY',
    appId: '1:296711123301:web:437e1d66b524236ea8318c',
    messagingSenderId: '296711123301',
    projectId: 'gymapp-8dacc',
    authDomain: 'gymapp-8dacc.firebaseapp.com',
    storageBucket: 'gymapp-8dacc.firebasestorage.app',
  );

}