// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm_wWHMCGGqJHEXLpqVNgYIjQaTVd1FNE',
    appId: '1:214350663878:web:76783f8cc8f9394834c7c7',
    messagingSenderId: '214350663878',
    projectId: 'gymapp-a66c6',
    authDomain: 'gymapp-a66c6.firebaseapp.com',
    storageBucket: 'gymapp-a66c6.firebasestorage.app',
    measurementId: 'G-451RXBH37D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnL0EU4vyyVNVur8MM-QrpURqbOLeyLBk',
    appId: '1:214350663878:android:d386014353f97db534c7c7',
    messagingSenderId: '214350663878',
    projectId: 'gymapp-a66c6',
    storageBucket: 'gymapp-a66c6.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTz7Pr23qL_F7lxSHuaTggtMvLojDXOr4',
    appId: '1:214350663878:ios:83549b18018f21cd34c7c7',
    messagingSenderId: '214350663878',
    projectId: 'gymapp-a66c6',
    storageBucket: 'gymapp-a66c6.firebasestorage.app',
    iosBundleId: 'com.churiah.gymAppV2',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTz7Pr23qL_F7lxSHuaTggtMvLojDXOr4',
    appId: '1:214350663878:ios:25a818d67486511e34c7c7',
    messagingSenderId: '214350663878',
    projectId: 'gymapp-a66c6',
    storageBucket: 'gymapp-a66c6.firebasestorage.app',
    iosBundleId: 'com.example.gymAppV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm_wWHMCGGqJHEXLpqVNgYIjQaTVd1FNE',
    appId: '1:214350663878:web:57e72b0a66b57f1d34c7c7',
    messagingSenderId: '214350663878',
    projectId: 'gymapp-a66c6',
    authDomain: 'gymapp-a66c6.firebaseapp.com',
    storageBucket: 'gymapp-a66c6.firebasestorage.app',
    measurementId: 'G-NF9WLZQE2V',
  );
}
